{
 "title": "Main dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c24-tp-1_node_1, 1c24-tp-1_node_2, 1c24-tp-1_node_3, 1c24-tp-1_cadvisor_1, 1c24-tp-1_grafana_1, 1c24-tp-1_graphite_1,  1c24-tp-1_nginx_1, 1c24-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Complete Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(transformNull(stats.gauges.myapp.*, 0), 3)"
    }
   ]
  },
  {
   "title": "Scenarios Lauched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "aliasByNode(transformNull(scale(stats.gauges.$server.scenarioCounts.*, 0.1), 0), 4)"
    }
   ]
  },
  {
   "title": "Requests States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.codes.200, 0.1), 0), 'Completed')"
    },
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.errors.ECONNRESET, 0.1), 0), 'Error Conection Reset')"
    },
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.pendingRequests, 0.1), 0), 'Pending')"
    },
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.codes.429, 0.1), 0), 'Limited')"
    },
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.errors.ETIMEDOUT, 0.1), 0), 'Error Timeout')"
    },
    {
     "target": "alias(transformNull(scale(stats.gauges.$server.codes.500, 0.1), 0), 'Error external API')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  }
 ]
}